name: Run UTS Website UI Test on Github Action

on:
  push:
    branches:
      - main

jobs:
  scrape:
    runs-on: windows-latest
    steps:
      - name: Checking out repo
        uses: actions/checkout@v2

      - name: Setting up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10

      - name: Install selenium
        run: pip install selenium
      - name: Install geckodriver Auto Installer
        run: pip install geckodriver_autoinstaller

      - name: Run the Python Script
        run: python3 uts_website_test.py