name: Run UTS Website UI Test on Github Action

on:
  push:
    branches:
      - main

jobs:
  scrape:
    runs-on: windows-latest
    steps:
      - name: Checking out repo
        uses: actions/checkout@v2

      - name: Setting up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Selenium
        run: pip install selenium

      - name: Run the Python Script
        run: python3 -m unittest test_uts_website.py