name: Run Selenium Grid UTS Website UI Test on Github Action

on:
  push:
    branches:
      - selenium-grid

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Checking out repo
        uses: actions/checkout@v2

      - name: Setting up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Selenium
        run: pip install selenium

      - name: Setup Docker Compose
        run: docker-compose -f docker-compose.yaml up -d

      - name: Give Write Access to Wait for Grid Script
        run: chmod +x wait-for-grid.sh
      
      - name: Wait for grid
        run: ./wait-for-grid.sh

      - name: Run the Python Script
        run: python3 -m unittest test_uts_website.py
      
      - name: Setdown Docker Compose
        run: docker-compose -f docker-compose.yaml down